# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Create temp file
        shell: bash
        run: |
          echo "{}" > src/UpdaterServer.DbMigrator/appsettings.secrets.json
          echo "{}" > test/UpdaterServer.TestBase/appsettings.secrets.json
          echo "{}" > test/UpdaterServer.HttpApi.Client.ConsoleTestApp/appsettings.secrets.json

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test test/UpdaterServer.EntityFrameworkCore.Tests/UpdaterServer.EntityFrameworkCore.Tests.csproj --no-build --verbosity normal --configuration Release
